services:
  - type: web
    name: tomato-disease-classifier
    env: python
    plan: free
    region: singapore
    pythonVersion: "3.12.12"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
