services:
  - type: web
    name: tomato-disease-classifier
    env: python
    plan: free
    region: singapore
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app

